"""Add generation field

Revision ID: c8dea6766159
Revises: f2b7ce2c8874
Create Date: 2023-10-31 21:39:07.729126

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c8dea6766159"
down_revision = "f2b7ce2c8874"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("generation", sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "generation")
    # ### end Alembic commands ###
