name: Run Test

on:
  pull_request:
    paths:
      - src/**
      - .github/workflows/test.yaml

env:
  APP_DIR: waffledotcom/src

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup python env
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.1"
          cache: "pip"

      - name: Install pip deps
        run: |
          python -m pip install --upgrade pip
          pip install -r "${GITHUB_WORKSPACE}/requirements.dev.txt"

      - name: Run tests
        run: |
          cd ${GITHUB_WORKSPACE}/${APP_DIR}/
          pytest --junit-xml=${GITHUB_WORKSPACE}/${APP_DIR}/test.xml ./

      - name: Test reports
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: backend tests
          path: "./${APP_DIR}/test.xml"
          reporter: java-junit
