name: Deploy-prod

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy prod
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.run_number }}
      ECR_REPOSITORY: waffledotcom-prod/waffledotcom-server

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1


    - name: Build, tag, and push image to ECR to be deployed for K8S
      id: build-image-k8s
      uses: docker/build-push-action@v4
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      with:
        context: .
        push: true
        tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        build-args: |
          ENV=prod
          DB_HOST=${{ secrets.DB_HOST_PROD }}
          DB_PORT=${{ secrets.DB_PORT_PROD }}
          DB_NAME=${{ secrets.DB_NAME_PROD }}
          DB_USERNAME=${{ secrets.DB_USERNAME_PROD }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD_PROD }}
